version: "3.7"
services:
  app:
    build:
      args:
        user: daniboy
        uid: 1000
      context: ./Docker
      dockerfile: Dockerfile
    image: php8-apllication-server
    container_name: php8-server-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - servernetwork
    environment:
      XDEBUG_CONFIG: "mode=debug,develop,develop start_with_request=yes client_host=host.docker.internal"

  db:
    image: mariadb:10.5.8
    container_name: php8-application-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./Docker/database:/var/lib/mysql:rw
    networks:
      - servernetwork
    ports:
      - 3306:3306

  nginx:
    image: nginx:alpine
    container_name: php8-application-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./Docker/nginx:/etc/nginx/conf.d
    networks:
      - servernetwork

networks:
  servernetwork:
    driver: bridge
